### ISSUE TITLE
Permission to use

### ISSUE THREAD

**Issue by pantierra** [whotwagner/mail2sms#1]
Hello,

Thanks for sharing your work. I have been used your blog entry to build up a similar system and I may apply some modifications. Of course, I would also like to share it. Therefore, I would like to know the license of the code here? It would be nice to attach an Open Source license like [MIT](https://opensource.org/licenses/MIT) to it.

Thank you

**Comment by whotwagner** [comment]
Hello,
Thanks for reading my blog. I added the GPL now, because I like the virus-thingy.
